pedido/urls.py
from django.urls import path
from . import views

app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.Criar.as_view(), name='criar'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

produto/urls.py
from django.urls import path
from . import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProdutos.as_view(), name="lista"),
    path('<slug:slug>', views.DetalheProduto.as_view(), name="detalhe"),
    path('adicionaraocarrinho/', views.AdicionarAoCarrinho.as_view(), name='adicionaraocarrinho'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='removerdocarrinho'),
    path('carrinho/', views.Carrinho.as_view(), name="carrinho"),
    path('resumodacompra/', views.ResumoDaCompra.as_view(), name="resumodacompra"),
    path('search/', views.Busca.as_view(), name="busca")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    
    # My apps
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/models.py
from django.db import models
from PIL import Image
from django.conf import settings
import os
from django.utils.text import slugify
from utils import utils

# Create your models here.
class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    imagem = models.ImageField(
        upload_to='produto_imagens/%Y/%m/', blank=True, null=True
    )
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(default=0, verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(default=0, verbose_name = 'Preço Promo.')
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Varíavel'),
            ('S', 'Simples'),
        )
    )

    def get_preco_formatado(self):
        return utils.formata_preco(self.preco_marketing)
    get_preco_formatado.short_description = 'Preço'

    def get_preco_promo_formatado(self):
        return utils.formata_preco(self.preco_marketing_promocional)
    get_preco_promo_formatado.short_description = 'Preço Promo.'

    @staticmethod
    def resize_image(img, new_width=800):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_height = img_pil.size

        if original_width <= new_width:
            print('Retornando, largura original menor que nova largura')
            img_pil.close()
            return
        
        new_heigth = round((original_height * new_width) / original_width)

        new_img = img_pil.resize((new_width, new_heigth), Image.LANCZOS)
        new_img.save(
            img_full_path,
            optimize=True,
            quality=50
        )
        print('Imagem foi redimensionada.')

    def save(self, *args, **kwargs):

        if not self.slug:
            self.slug = f'{slugify(self.nome)}'

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self) -> str:
        return self.nome

class Variacao(models.Model):
    nome = models.CharField(max_length=255, blank=True, null=True)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE, blank=True, null=True, related_name='variacoes_set')
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self) -> str:
        return self.nome or self.produto.nome
    
    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'
    



    

produto/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponse as HttpResponse
from django.shortcuts import redirect, get_object_or_404, render
from django.views.generic import ListView
from django.views.generic import DetailView, View, ListView
from django.contrib import messages

from django.contrib.auth.decorators import login_required

from django.db.models import Q

from . import models
from perfil import models as PerfilModels

# Create your views here.


class ListaProdutos(ListView):
    model = models.Produto
    template_name = 'produto/index.html'
    context_object_name = 'produtos'
    paginate_by = 3
    ordering = ['-pk']

class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detail.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'

class AdicionarAoCarrinho(View):
    

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:

        http_referer = self.request.META.get('HTTP_REFERER', 'produto:lista')
        variacao_id = self.request.GET.get('vid')
        
        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe'
            )

            return redirect(http_referer)

        variacao = get_object_or_404(models.Variacao, pk=variacao_id)
        produto = variacao.produto

        produto_id = produto.pk
        produto_nome = produto.nome
        variacao_nome = variacao.nome
        variacao_estoque = variacao.estoque
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = 1
        slug = produto.slug
        imagem = produto.imagem.url if produto.imagem else 'None'

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho:dict = self.request.session['carrinho']

        if variacao_estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente'
            )
            return redirect(http_referer)

        if variacao_id in carrinho:
            # Variação existe no carrinho
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += 1

            if variacao_estoque < quantidade_carrinho:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {quantidade_carrinho}x no '
                    f'produto "{produto_nome}". Adicionamos {variacao_estoque}x '
                    'no seu carrinho.'
                )
                quantidade_carrinho = variacao_estoque
            
            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = preco_unitario_promocional * quantidade_carrinho

        else:
            #  Variação não existe no carrinho
            carrinho[variacao_id] = {
                'produto_id' : produto_id,
                'produto_nome' : produto_nome,
                'variacao_nome' : variacao_nome,
                'variacao_id' : variacao_id,
                'preco_unitario' : preco_unitario,
                'preco_unitario_promocional' : preco_unitario_promocional,
                'preco_quantitativo': preco_unitario,
                'preco_quantitativo_promocional': preco_unitario_promocional,
                'quantidade' : quantidade,
                'slug' : slug,
                'imagem' : imagem,
            }
        
        self.request.session.save()

        messages.success(
            self.request,
            f'Produto {produto_nome} {variacao_nome} adicionado ao seu '
            f'carrinho {carrinho[variacao_id]["quantidade"]}x'
        )

        return redirect(http_referer)

class RemoverDoCarrinho(View):
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        http_referer = request.META.get('HTTP_REFERER', 'produto:lista')
        variacao_id = request.GET.get('vid')

        if not variacao_id:
            return redirect(http_referer)
        
        if not request.session.get('carrinho'):
            return redirect(http_referer)
        
        if variacao_id not in request.session.get('carrinho'):
            return redirect(http_referer)
        
        carrinho = request.session['carrinho'][variacao_id]

        messages.success(
            request,
            f'Produto {carrinho["produto_nome"]} {carrinho["variacao_nome"]} '
            'foi removido do seu carrinho.'
        )

        del request.session['carrinho'][variacao_id]
        request.session.save()

        return redirect(http_referer)

class Carrinho(View):
    def get(self, *args, **kwargs):
        contexto = {
            'carrinho': self.request.session.get('carrinho', {})
        }
        return render(self.request, 'produto/cart.html', contexto)
    
class Busca(ListaProdutos):
    def get_queryset(self) -> QuerySet[Any]:

        termo = self.request.GET.get('termo')
        qs = super().get_queryset()
        
        if not termo:
            return qs

        qs = qs.filter(
            Q(nome__icontains=termo) |
            Q(descricao_curta__icontains=termo) |
            Q(descricao_longa__icontains=termo)
        )

        return qs

class ResumoDaCompra(DetailView):
    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:

        if not request.user.is_authenticated:
            return redirect('perfil:criar')
        
        if not request.session.get('carrinho'):
            messages.error(
                request,
                'Seu carrinho está vazio'
            )

            return redirect('produto:lista')
        
        perfil = PerfilModels.Perfil.objects.filter(usuario=request.user).first()

        if not perfil:
            messages.error(
                request,
                'Usuário sem perfil'
            )

            return redirect('perfil:criar')

        contexto = {
            'usuario': request.user,
            'perfil': perfil,
            'carrinho': request.session['carrinho']
        }

        return render(request, 'produto/resumodacompra.html', contexto)

produto/templates/produto/cart.html
{% extends "base.html" %}
{% load om_filters %}
{% load static %}

{% block title %}
    Carrinho - 
{% endblock title %}

{% block content %}

    {% if carrinho %}

        <div class="row mt-3">
            <div class="col">
                <h3>Carrinho de compras</h3>
                <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>
                

                {% include "global/partials/_cart.html" %}
            </div>
        </div>

        <div class="row mt-3">
            <div class="col-lg">
                <p class='lead'>Total no carrinho</p>

                <div class='table-responsive'>
                    <table class="table">
                        <tr>
                            <td class="font-weight-bold">Total</td>
                            <td>{{carrinho | cart_totals | formata_preco}}</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="col-lg mt-auto">

                {% if request.user.is_authenticated %}
                    <a class="btn btn-lg btn-block btn-primary" href="{% url "produto:resumodacompra" %}">
                        Comprar
                    </a>
                {% else %}
                    <a class="btn btn-lg btn-block btn-primary" href="{% url "perfil:criar" %}">
                        Entrar ou cadastrar e comprar
                    </a>
                {% endif %}
            </div>
        </div>

    {% else %}
        <div class="row mt-3">
            <div class="col">
                <h3>Carrinho de compras</h3>
                <p class="lead">Não há produtos no seu carrinho.</p>
            </div>
        </div>
    {% endif %}

{% endblock content %}

produto/templates/produto/detail.html
{% extends "base.html" %}
{% load om_filters %}


{% block title %}
    {{produto.nome}} - 
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        {% if produto.imagem %}
                            <img class="img-fluid" src="{{produto.imagem.url}}">
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{produto.nome}}</h1>
                    <p class="lead">{{produto.descricao_curta | linebreaks}}</p>
                    <p class="lead">
                        {% if produto.preco_marketing_promocional %}
                            <span id="variation-preco" class="lead product-price">{{produto.preco_marketing_promocional | formata_preco}}</span>
                            <span id="variation-preco-promocional"
                            class="lead product-old-price text-muted">{{produto.preco_marketing | formata_preco}}</span>
                        {% else %}
                            <span id="variation-preco" class="lead product-price">{{produto.preco_marketing | formata_preco}}</span>
                        {% endif %}
                    </p>

                    <form action="{% url "produto:adicionaraocarrinho" %}" id="form-add-to-cart">
                        <div class="form-group">
                            <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                {% for variacao in produto.variacoes_set.all %}
                                    {% if variacao.preco_promocional %}
                                        <option data-preco="{{variacao.preco_promocional | formata_preco}}" data-preco-promocional="{{variacao.preco | formata_preco}}" value="{{variacao.pk}}">
                                            {% if variacao.nome %}
                                                {{variacao.nome}}
                                            {% else %}
                                                {{variacao}}
                                            {% endif %}
                                        </option>
                                    {% else %}
                                        <option data-preco="{{variacao.preco | formata_preco}}" value="{{variacao.pk}}">
                                            {% if variacao.nome %}
                                                {{variacao.nome}}
                                            {% else %}
                                                {{variacao}}
                                            {% endif %}
                                        </option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>

                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>

                    </form>


                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="mt-5 mb-5">
                    <h2 class="text-center">{{produto.nome}}</h2>
                    {{produto.descricao_longa | linebreaks}}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

produto/templates/produto/index.html
{% extends "base.html" %}
{% load om_filters %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="card-columns">

                {% for produto in produtos %}
                    <div class="card">
                        {% if produto.imagem %}
                        <a href="{% url "produto:detalhe" produto.slug %}">
                            <img class="card-img-top" src="{{produto.imagem.url}}"
                            alt="{{produto.nome}}">
                        </a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{produto}}</h5>
                            <p class="card-text">{{produto.descricao_curta}}</p>
                            <div class="container product-price-block text-center">
                                {% if produto.preco_marketing_promocional %}
                                    <span class="product-price">
                                        {{produto.preco_marketing_promocional | formata_preco}}
                                    </span>
                                {% else %}
                                    <span class="product-price">
                                        {{produto.preco_marketing | formata_preco}}
                                    </span>
                                {% endif %}

                                {% if produto.preco_marketing_promocional %}
                                    <span class="product-old-price text-muted">
                                        {{produto.preco_marketing | formata_preco}}
                                    </span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="card-footer bg-transparent border-top-light-custom text-center">
                            <a href="{% url "produto:detalhe" produto.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Comprar
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="row mt-3 center">
        <div class="col">
            {% include "global/partials/_pagination.html" %}
        </div>
    </div>
{% endblock content %}

produto/templates/produto/resumodacompra.html
{% extends "base.html" %}
{% load om_filters %}

{% block title %}
    Resumo da compra - 
{% endblock title %}

{% block content %}

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li>
        <li class="nav-item">
            <a class="nav-link nav-cart-link active" href="#">
                <span class="nav-cart-text mr-1">
                    Carrinho
                </span>
                <span class="nav-cart-count mr-1">
                    <strong>109x</strong>
                </span>
                <span class="nav-cart-icon mr-2">
                    <i class="fas fa-shopping-cart"></i>
                </span>
            </a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
</div>
</nav>

<main class="container mt-4 mb-4">

<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>
        <p>Caso precise editar, <a href="{% url "perfil:criar" %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{usuario.first_name}}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{usuario.last_name}}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{perfil.idade}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{perfil.data_nascimento}}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{perfil.cpf}}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{usuario.email}}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        <p>Caso precise editar, <a href="{% url "perfil:criar" %}">clique aqui</a></p>
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{perfil.endereco}}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{perfil.numero}}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{perfil.complemento}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{perfil.bairro}}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{perfil.cidade}}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{perfil.estado}}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{perfil.cep}}</dd>
        </dl>
    </div>
</div>


<div class="row mt-3">
    <div class="col">
        <h3>Resumo do carrinho</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include "global/partials/_cart.html" %}

    </div>
</div>
<div class="row mt-3">
    <div class="col">
        <p class="lead text-center">
            <span class="font-weight-bold text-center">Total do carrinho:</span> {{carrinho | cart_totals | formata_preco}}
        </p>
    </div>
</div>

<div class="row">
    <div class="col">
        <a class="btn btn-block btn-primary btn-lg" href="{% url "pedido:salvarpedido" %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>

{% endblock content %}